name: Update Blog URLs
on:
  workflow_dispatch:
  schedule:
    - cron: 0 15 * * *
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v2.0.0
        with:
          feed-url: https://dalrankov.me/feed.xml
          readme-section: posts
          branch: main